# Generated by Django 3.0.4 on 2020-03-27 16:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='foto/jogo', verbose_name='Foto')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CapituloJogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='foto/capitulo', verbose_name='Foto')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now)),
                ('iframe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apenas a Url do youtube')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.JogoModel', verbose_name='jogo')),
            ],
            options={
                'verbose_name': 'Capítulo Jogo',
                'verbose_name_plural': 'Capitulos dos jogos',
                'ordering': ['nome'],
            },
        ),
    ]
