# Generated by Django 3.0.4 on 2020-03-27 18:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulojogomodel',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='jogomodel',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Conteúdo'),
        ),
    ]
